### ISSUE TITLE
Commonmark 2

### ISSUE THREAD

**Issue by duncanmcclean** [torchlight-api/torchlight-commonmark-php#2]
Just started a fresh Laravel app (👀), which comes with Commonmark v2 pre-installed - see [`composer.json`](https://github.com/laravel/framework/blob/8.x/composer.json#L25).

Although, when I go to pull in this Torchlight Commonmark package into my app, it doesn't let me as it only supports v1.5 upwards.

I can't really downgrade because I'm using a v2 extension for handling front-matter stuff. I forked this project to try and update it for v2 but I failed 😂 

Not sure how much work would be involved in making it work with Commonmark v2?

**Comment by aarondfrancis** [comment]
I think I can tackle this tomorrow! I've got the day off. Should be easy 🤞

**Comment by duncanmcclean** [comment]
Thanks dude! 🙏

**Comment by duncanmcclean** [comment]
Just tested the v2 version you've got sitting in `main` and it works perfectly! Thanks man!

**Comment by aarondfrancis** [comment]
Ha! Johnny on the spot! Glad to hear that. I'm almost done and I'll tag a new release. Thanks for testing!

**Comment by aarondfrancis** [comment]
Released! Thanks for the nudge to get this updated.
